### ISSUE TITLE
Public or private

### ISSUE THREAD

**Issue by xji3** [stats-comp-algo-software-2023/YuzhengDun1999#1]
@aki-nishimura
Do you want to make these repositories private?

**Comment by aki-nishimura** [comment]
Thanks for the heads-up, all good — these repos are created as public copies of the private ones so that students in my course can practice peer review processes. 

(I guess you saw my activities pop up in your notification? Funny thing that, unless you explicitly try to keep it private, everything you do is visible to everyone nowadays...)

**Comment by xji3** [comment]
Reviewer 1 is happy now.
